#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
W1z4rD V1510n -- Rich Multi-Modal Concept Stream Trainer
========================================================
Uses EVERY available modality simultaneously so the neural fabric builds
cross-stream concept neurons that fire regardless of input channel:

  IMAGE     -- clean concept photograph or generated graphic
  TEXT      -- structured spans with spatial position (x_frac, y_frac)
  KEYBOARD  -- character-by-character typing triggers txt:word_ labels
  AUDIO     -- AWS Polly neural speech, 16 kHz PCM wrapped in WAV
  TEMPORAL  -- lifecycle sequences bridge frames via Hebbian decay

DATA QUALITY IS THE FOUNDATION.
Before any byte reaches the training endpoint it passes ALL gates:
  1. Image decodable as JPEG/PNG
  2. Width >= 200px AND height >= 200px
  3. Pixel variance > 100 (not blank / not solid color for non-color concepts)
  4. File size > 8 KB (not a tiny icon or placeholder)
  5. Source category matches concept (Wikipedia title verified)

Synthetic images (colors, shapes, numbers) are generated by Pillow and are
therefore 100% semantically correct by construction.

VIDEO PIPELINE (Archive.org):
  python train_concept_streams.py --video-prep
  Downloads Prelinger/ephemeral archive films, extracts frames at 2 fps and
  16 kHz audio, trains as temporal image+audio sequences.

USAGE:
  # Quick experiment -- 10 concepts, all modalities, probe results
  python train_concept_streams.py --concepts 10

  # Full Stage 0 (82 concepts)
  python train_concept_streams.py --concepts all

  # Prep data without training
  python train_concept_streams.py --prep-only --concepts all

  # Only cross-modal probe (node must be running with training already done)
  python train_concept_streams.py --probe-only

  # Archive.org video pipeline
  python train_concept_streams.py --video-prep --video-train

PYTHON: Use C:/Python313/python.exe (has Pillow, boto3, httpx, numpy)
"""

from __future__ import annotations
import argparse, base64, io, json, os, re, struct, sys, time, hashlib

# Ensure UTF-8 output on Windows (cp1252 can't handle arrows/checkmarks)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import httpx
import numpy as np

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    sys.exit("Missing: pip install Pillow")

try:
    import boto3
    _HAS_BOTO3 = True
except ImportError:
    _HAS_BOTO3 = False

# ---------------------------------------------------------------------------
# Paths & config
# ---------------------------------------------------------------------------
ROOT       = Path(__file__).resolve().parents[1]
DATA_DIR   = ROOT / "data" / "concept_streams"
VIDEO_DIR  = ROOT / "data" / "video_streams"
NODE_URL   = "http://127.0.0.1:8090"
AWS_PROFILE = "FountainServer"
AWS_REGION  = "us-east-1"
POLLY_BUCKET = "awspollyfiles"

# Quality gates
MIN_IMAGE_W    = 200
MIN_IMAGE_H    = 200
MIN_FILE_BYTES = 8_000
MIN_VARIANCE   = 80       # skip blank/solid images (except generated)
MAX_IMAGES_PER = 4        # max downloaded images per concept

# Training params
LR_ANCHOR   = 1.5   # first exposure: stamp hard
LR_CONTEXT  = 1.2   # definition frame
LR_SCENE    = 1.0   # scene composition / multi-object
LR_SEQ      = 0.9   # sequence frames
TEMP_TAU    = 2.0   # seconds -- Hebbian temporal decay

# ---------------------------------------------------------------------------
# Concept registry
# ---------------------------------------------------------------------------
@dataclass
class Concept:
    word: str
    type: str           # concrete | color | shape | number | action | descriptor | abstract
    wiki_title: str     # Wikipedia article title
    definition: str
    example: str        # short example sentence
    related: list[str] = field(default_factory=list)
    color_rgb: Optional[tuple] = None   # for color type only

CONCEPTS: list[Concept] = [
    # -- Body ------------------------------------------------------------------
    Concept("eyes",     "concrete", "Human_eye",
            "Eyes are the organs you use to see. They detect light and send images to your brain.",
            "Open your eyes and look at the sky.", ["see","light","brain","organ"]),
    Concept("ears",     "concrete", "Ear",
            "Ears are the organs you use to hear sounds.",
            "Your ears pick up every sound around you.", ["hear","sound","organ"]),
    Concept("nose",     "concrete", "Human_nose",
            "A nose is the organ on your face that you use to smell and breathe.",
            "The nose filters the air you breathe.", ["smell","breathe","face","organ"]),
    Concept("mouth",    "concrete", "Mouth",
            "A mouth is the opening in your face used for eating, drinking, and speaking.",
            "Open your mouth wide.", ["eat","speak","face","taste"]),
    Concept("hand",     "concrete", "Hand",
            "A hand is the part of your arm at the end, with fingers for grasping and touching.",
            "Pick it up with your hand.", ["fingers","grasp","touch","arm"]),
    Concept("heart",    "concrete", "Heart",
            "A heart is the organ in your chest that pumps blood through your body.",
            "Your heart beats about 70 times per minute.", ["pump","blood","chest","organ"]),
    Concept("brain",    "concrete", "Brain",
            "A brain is the organ inside your skull that controls your thoughts, feelings, and actions.",
            "The brain never stops working.", ["think","organ","skull","nervous"]),
    Concept("skin",     "concrete", "Skin",
            "Skin is the outer covering of your body that protects you and helps you feel touch.",
            "Skin is the body's largest organ.", ["protect","touch","body","organ"]),

    # -- Animals ---------------------------------------------------------------
    Concept("dog",      "concrete", "Dog",
            "A dog is a domestic animal kept as a pet. Dogs are loyal and friendly.",
            "The dog wagged its tail happily.", ["animal","pet","loyal","fur"]),
    Concept("cat",      "concrete", "Cat",
            "A cat is a small domestic animal with soft fur, sharp claws, and whiskers.",
            "The cat curled up on the warm cushion.", ["animal","pet","fur","whiskers"]),
    Concept("bird",     "concrete", "Bird",
            "A bird is an animal with wings and feathers that can usually fly.",
            "The bird sang a beautiful song.", ["fly","wings","feathers","animal"]),
    Concept("fish",     "concrete", "Fish",
            "A fish is an animal that lives in water and breathes through gills.",
            "The fish swam silently through the water.", ["water","gills","swim","animal"]),
    Concept("horse",    "concrete", "Horse",
            "A horse is a large four-legged animal used for riding and pulling loads.",
            "The horse galloped across the field.", ["ride","animal","mane","hooves"]),
    Concept("elephant", "concrete", "Elephant",
            "An elephant is a very large animal with a long trunk, big ears, and tusks.",
            "The elephant lifted the log with its trunk.", ["trunk","animal","large","tusks"]),
    Concept("butterfly","concrete", "Butterfly",
            "A butterfly is an insect with large colorful wings that flies from flower to flower.",
            "The butterfly landed on the flower.", ["insect","wings","flower","color"]),

    # -- Food ------------------------------------------------------------------
    Concept("apple",    "concrete", "Apple",
            "An apple is a round fruit that grows on trees. Apples can be red, green, or yellow.",
            "She bit into the crisp red apple.", ["fruit","red","tree","food","sweet"]),
    Concept("banana",   "concrete", "Banana",
            "A banana is a long curved yellow fruit with soft sweet flesh inside.",
            "Peel the banana before eating it.", ["fruit","yellow","tropical","food"]),
    Concept("bread",    "concrete", "Bread",
            "Bread is a food baked from flour, water, and yeast.",
            "Fresh bread smells amazing.", ["food","bake","flour","wheat"]),
    Concept("milk",     "concrete", "Milk",
            "Milk is a white liquid produced by mammals to feed their young.",
            "Pour a glass of cold milk.", ["white","liquid","food","cow","nutrient"]),
    Concept("water",    "concrete", "Water",
            "Water is a clear liquid that all living things need to survive.",
            "Drink eight glasses of water every day.", ["liquid","clear","life","drink","river"]),
    Concept("egg",      "concrete", "Egg",
            "An egg is an oval object laid by birds and reptiles, and a common food.",
            "Crack two eggs into the bowl.", ["food","oval","bird","protein"]),
    Concept("rice",     "concrete", "Rice",
            "Rice is a grain grown in flooded fields. It is the staple food for more than half the world.",
            "Boil the rice for twenty minutes.", ["grain","food","staple","cook"]),
    Concept("sugar",    "concrete", "Sugar",
            "Sugar is a sweet crystalline substance found in fruits and refined from sugarcane.",
            "Add a spoonful of sugar to sweeten it.", ["sweet","food","energy","white"]),

    # -- Colors ----------------------------------------------------------------
    Concept("red",    "color",  "Red",    "Red is a warm, bright color seen in fire, blood, and ripe strawberries.",
            "The fire truck is red.", ["color","warm","fire","blood"], color_rgb=(220,50,47)),
    Concept("blue",   "color",  "Blue",   "Blue is a cool color like the sky and the ocean.",
            "The clear sky is blue.", ["color","cool","sky","ocean"], color_rgb=(38,139,210)),
    Concept("green",  "color",  "Green",  "Green is the color of plants and grass.",
            "The leaves are green.", ["color","plant","nature","grass"], color_rgb=(133,153,0)),
    Concept("yellow", "color",  "Yellow", "Yellow is a bright warm color like the sun and lemons.",
            "The sun is bright yellow.", ["color","warm","sun","bright"], color_rgb=(181,137,0)),
    Concept("white",  "color",  "White",  "White is a color that reflects all light. Snow and clouds are white.",
            "The snow looks pure white.", ["color","light","snow","pure"], color_rgb=(253,246,227)),
    Concept("black",  "color",  "Black",  "Black is the absence of reflected light. Night and shadows are black.",
            "The night sky is black.", ["color","dark","night","shadow"], color_rgb=(0,0,0)),
    Concept("orange", "color",  "Orange_color", "Orange is a warm color between red and yellow.",
            "The sunset is orange.", ["color","warm","sunset","fruit"], color_rgb=(203,75,22)),
    Concept("purple", "color",  "Purple", "Purple is a color made by mixing red and blue.",
            "The grapes are deep purple.", ["color","royal","grape","mix"], color_rgb=(108,113,196)),

    # -- Numbers ---------------------------------------------------------------
    Concept("zero",    "number", "0",     "Zero is the number that represents nothing or no amount.",
            "The score is zero to zero.", ["number","nothing","count","math"], ),
    Concept("one",     "number", "1",     "One is the first counting number. It represents a single item.",
            "There is one sun in our sky.", ["number","single","first","count"]),
    Concept("two",     "number", "2",     "Two is a number that represents a pair of things.",
            "You have two hands.", ["number","pair","count","twice"]),
    Concept("ten",     "number", "10",    "Ten is the number after nine. We count in tens because humans have ten fingers.",
            "Count to ten slowly.", ["number","count","decimal","fingers"]),
    Concept("hundred", "number", "100",   "A hundred is the number equal to ten times ten, written as 100.",
            "There are one hundred cents in a dollar.", ["number","count","percent","math"]),

    # -- Shapes ----------------------------------------------------------------
    Concept("circle",    "shape", "Circle",    "A circle is a perfectly round shape where every point on the edge is the same distance from the center.",
            "A wheel is shaped like a circle.", ["shape","round","center","geometry"]),
    Concept("square",    "shape", "Square",    "A square is a shape with four equal sides and four right angles.",
            "A chessboard is made of squares.", ["shape","sides","equal","geometry"]),
    Concept("triangle",  "shape", "Triangle",  "A triangle is a shape with three sides and three angles.",
            "A yield sign is a triangle.", ["shape","three","sides","geometry"]),
    Concept("rectangle", "shape", "Rectangle", "A rectangle is a shape with four sides where opposite sides are equal.",
            "This door is a rectangle.", ["shape","four","sides","geometry"]),
    Concept("sphere",    "shape", "Sphere",    "A sphere is a perfectly round three-dimensional shape like a ball.",
            "The Earth is roughly a sphere.", ["shape","round","3d","ball","geometry"]),

    # -- Nature ----------------------------------------------------------------
    Concept("tree",     "concrete", "Tree",     "A tree is a tall plant with a woody trunk, branches, and leaves.",
            "The oak tree grew for a hundred years.", ["plant","trunk","leaves","nature","wood"]),
    Concept("sun",      "concrete", "Sun",      "The sun is the star at the center of our solar system. It provides light and heat for all life on Earth.",
            "The sun rises in the east.", ["star","light","heat","energy","sky"]),
    Concept("moon",     "concrete", "Moon",     "The moon is Earth's natural satellite that orbits our planet.",
            "The full moon lit up the night.", ["orbit","satellite","night","tide"]),
    Concept("rain",     "concrete", "Rain",     "Rain is water that falls from clouds in the sky to the ground.",
            "The rain soaked the dry earth.", ["water","cloud","weather","fall"]),
    Concept("river",    "concrete", "River",    "A river is a large stream of fresh water flowing across the land.",
            "The river flows down to the sea.", ["water","flow","fresh","land"]),
    Concept("ocean",    "concrete", "Ocean",    "An ocean is a vast body of salt water that covers most of Earth's surface.",
            "The ocean is home to millions of species.", ["water","salt","vast","marine"]),
    Concept("mountain", "concrete", "Mountain", "A mountain is a large landform that rises steeply above the surrounding land.",
            "We hiked to the top of the mountain.", ["land","high","rock","terrain"]),
    Concept("sky",      "concrete", "Sky",      "The sky is the region of the atmosphere above the Earth. It appears blue during the day.",
            "The sky is clear and blue today.", ["blue","atmosphere","above","clouds"]),

    # -- Family ----------------------------------------------------------------
    Concept("family",   "concrete", "Family",  "A family is a group of people related by blood, marriage, or adoption who care for each other.",
            "We spend holidays together as a family.", ["people","care","love","together"]),
    Concept("mother",   "concrete", "Mother",  "A mother is a female parent who gives birth to or raises children.",
            "My mother read me a story every night.", ["parent","female","care","nurture"]),
    Concept("father",   "concrete", "Father",  "A father is a male parent who helps raise and care for children.",
            "My father taught me how to ride a bike.", ["parent","male","care","guide"]),
    Concept("friend",   "concrete", "Friendship", "A friend is someone you know well, enjoy spending time with, and care about.",
            "A good friend listens when you are sad.", ["people","care","trust","bond"]),
    Concept("teacher",  "concrete", "Teacher", "A teacher is a person whose job is to help others learn and understand new things.",
            "The teacher explained the problem clearly.", ["school","learn","guide","knowledge"]),

    # -- Actions ---------------------------------------------------------------
    Concept("run",   "action", "Running",   "Run means to move quickly on your feet, faster than walking.",
            "She ran the whole length of the field.", ["move","fast","feet","speed"]),
    Concept("eat",   "action", "Eating",    "Eat means to put food in your mouth, chew it, and swallow it for nourishment.",
            "We eat three meals a day.", ["food","chew","swallow","nourish"]),
    Concept("sleep", "action", "Sleep",     "Sleep is a natural rest state when your body and mind recover and restore themselves.",
            "He slept for eight hours.", ["rest","night","dream","restore"]),
    Concept("think", "action", "Thought",   "Think means to use your mind to reason, form ideas, and solve problems.",
            "Think carefully before you answer.", ["mind","reason","idea","solve"]),
    Concept("learn", "action", "Learning",  "Learn means to gain new knowledge or skills through study, experience, or being taught.",
            "You learn something new every day.", ["knowledge","skill","study","grow"]),
    Concept("grow",  "action", "Plant_growth", "Grow means to get bigger or develop over time, as plants and animals do.",
            "The seedling grew into a tall tree.", ["develop","bigger","time","change"]),
    Concept("love",  "action", "Love",      "Love is a strong feeling of deep affection and care for someone or something.",
            "She loves her family deeply.", ["affection","care","bond","emotion"]),

    # -- Descriptors -----------------------------------------------------------
    Concept("big",   "descriptor", "Large",  "Big means large in size, more than usual.",
            "An elephant is big.", ["size","large","great","tall"]),
    Concept("small", "descriptor", "Small",  "Small means little in size, less than usual.",
            "An ant is very small.", ["size","tiny","little","minor"]),
    Concept("hot",   "descriptor", "Heat",   "Hot means having a high temperature, like fire or boiling water.",
            "The soup is too hot to eat yet.", ["temperature","warm","fire","energy"]),
    Concept("cold",  "descriptor", "Cold",   "Cold means having a low temperature, like ice or winter air.",
            "The ice is cold to the touch.", ["temperature","ice","winter","freeze"]),
    Concept("soft",  "descriptor", "Soft",   "Soft means easy to press or bend, not hard. Pillows and cotton are soft.",
            "The kitten's fur is very soft.", ["texture","gentle","press","yield"]),
    Concept("hard",  "descriptor", "Hard",   "Hard means difficult to scratch or bend, solid and firm. Rocks and metal are hard.",
            "The rock is hard and heavy.", ["texture","solid","firm","resist"]),
    Concept("fast",  "descriptor", "Speed",  "Fast means moving or happening quickly.",
            "A cheetah is the fastest land animal.", ["speed","quick","time","move"]),
    Concept("slow",  "descriptor", "Slow",   "Slow means moving or happening at a low speed.",
            "The turtle moves very slowly.", ["speed","gentle","time","pace"]),

    # -- Abstract concepts -----------------------------------------------------
    Concept("language", "abstract", "Language", "Language is a system of words and rules humans use to communicate.",
            "Language lets us share ideas and feelings.", ["words","communicate","grammar","system"]),
    Concept("question", "abstract", "Question", "A question is a sentence that asks for information or an answer.",
            "Ask a good question and you will learn.", ["ask","information","curiosity","learn"]),
    Concept("answer",   "abstract", "Answer",   "An answer is a response to a question that gives the information requested.",
            "Every question deserves a thoughtful answer.", ["response","information","reply","truth"]),
    Concept("word",     "abstract", "Word",     "A word is a unit of language that carries meaning.",
            "Every sentence is built from words.", ["language","meaning","unit","symbol"]),
    Concept("sentence", "abstract", "Sentence", "A sentence is a group of words that expresses a complete thought.",
            "Write your ideas in complete sentences.", ["words","thought","grammar","complete"]),
    Concept("number",   "abstract", "Number",   "A number is a symbol used to count, measure, and label things.",
            "Numbers are the language of mathematics.", ["count","measure","math","symbol"]),
    Concept("time",     "abstract", "Time",     "Time is the ongoing sequence of events from the past through the present to the future.",
            "Time moves at the same rate for everyone.", ["past","present","future","sequence"]),
    Concept("energy",   "abstract", "Energy",   "Energy is the ability to do work or cause change. Food and sunlight are sources of energy.",
            "Energy cannot be created or destroyed.", ["work","change","physics","power"]),
    Concept("gravity",  "abstract", "Gravity",  "Gravity is the force that pulls objects toward each other. Earth's gravity keeps us on the ground.",
            "Gravity keeps the moon in orbit.", ["force","pull","mass","physics"]),
    Concept("science",  "abstract", "Science",  "Science is the study of the natural world through observation and experiments.",
            "Science helps us understand how things work.", ["study","observe","experiment","knowledge"]),
    Concept("math",     "abstract", "Mathematics", "Math is the study of numbers, shapes, and patterns used to count, measure, and solve problems.",
            "Math is the foundation of all science.", ["numbers","patterns","logic","solve"]),
    Concept("music",    "abstract", "Music",    "Music is sound organized in time with rhythm, melody, and harmony.",
            "Music can express emotions that words cannot.", ["sound","rhythm","melody","art"]),
    Concept("art",      "abstract", "Art",      "Art is the expression of human creativity through painting, sculpture, music, and other forms.",
            "Art communicates across languages and cultures.", ["create","express","beauty","culture"]),
]

# ---------------------------------------------------------------------------
# Domain meta-streams  (fire as temporal concept chains)
# ---------------------------------------------------------------------------
META_STREAMS = {
    "marketing_psychology": [
        ["attention", "awareness", "curiosity", "interest"],
        ["desire", "want", "need", "emotion", "motivation"],
        ["trust", "credibility", "proof", "confidence"],
        ["urgency", "scarcity", "decision", "action"],
        ["satisfaction", "loyalty", "word", "advocate"],
    ],
    "medical_reasoning": [
        ["symptom", "pain", "duration", "onset", "severity"],
        ["history", "patient", "risk", "factor"],
        ["examine", "observe", "measure", "test", "analyze"],
        ["differential", "diagnosis", "confirm", "treat"],
        ["prescription", "therapy", "monitor", "recover"],
    ],
    "scientific_method": [
        ["observe", "notice", "phenomenon", "wonder", "question"],
        ["predict", "hypothesize", "suppose", "model", "theory"],
        ["design", "experiment", "control", "variable", "test"],
        ["measure", "collect", "data", "record", "analyze"],
        ["conclude", "support", "refute", "publish", "replicate"],
    ],
    "metacognition": [
        ["perceive", "sense", "attend", "notice", "aware"],
        ["encode", "interpret", "understand", "relate", "context"],
        ["store", "remember", "associate", "connect", "link"],
        ["retrieve", "recall", "recognize", "match", "compare"],
        ["reason", "infer", "deduce", "conclude", "decide"],
        ["plan", "goal", "strategy", "execute", "monitor"],
        ["evaluate", "reflect", "adjust", "learn", "improve"],
    ],
    "causal_reasoning": [
        ["cause", "reason", "because", "factor", "source"],
        ["condition", "trigger", "event", "state", "situation"],
        ["process", "chain", "sequence", "step", "flow"],
        ["effect", "result", "consequence", "outcome", "change"],
        ["feedback", "loop", "cycle", "repeat", "reinforce"],
    ],
    "language_structure": [
        ["noun", "subject", "thing", "person", "place"],
        ["verb", "action", "state", "being", "move"],
        ["adjective", "describe", "modify", "quality", "size"],
        ["sentence", "subject", "predicate", "complete", "thought"],
        ["paragraph", "topic", "support", "conclude", "transition"],
    ],
}

# Scene pairs -- concepts that naturally co-occur for decomposition training
SCENE_PAIRS = [
    ("apple", "banana"), ("dog", "cat"), ("sun", "moon"),
    ("river", "mountain"), ("mother", "father"), ("circle", "square"),
    ("hot", "cold"), ("big", "small"), ("fast", "slow"),
    ("science", "math"), ("art", "music"), ("question", "answer"),
]

# Lifecycle sequences (concept -> related chain, for temporal training)
LIFECYCLE_SEQUENCES = [
    ["seed", "sprout", "plant", "tree", "flower", "fruit", "apple", "eat", "energy"],
    ["rain", "cloud", "water", "river", "ocean", "evaporate", "cloud", "rain"],
    ["egg", "hatch", "chick", "bird", "fly", "sky", "wind", "free"],
    ["baby", "child", "learn", "grow", "teenager", "adult", "teach", "wisdom"],
    ["question", "think", "reason", "hypothesize", "test", "answer", "learn", "question"],
    ["cold", "ice", "freeze", "winter", "snow", "melt", "water", "warm", "summer", "hot"],
    ["eye", "see", "light", "color", "red", "blue", "green", "beauty", "art"],
    ["word", "sentence", "paragraph", "story", "language", "communicate", "understand", "learn"],
    ["number", "count", "add", "multiply", "pattern", "math", "science", "discover"],
    ["attention", "interest", "desire", "trust", "action", "satisfaction", "loyalty"],
]

# ---------------------------------------------------------------------------
# Synthetic image generators (perfect by construction)
# ---------------------------------------------------------------------------

def generate_color_image(concept: Concept) -> bytes:
    rgb = concept.color_rgb or (128, 128, 128)
    img = Image.new("RGB", (400, 300), color=rgb)
    draw = ImageDraw.Draw(img)
    # White label bar at bottom
    draw.rectangle([0, 250, 400, 300], fill=(255, 255, 255))
    draw.text((200, 275), concept.word.upper(), fill=(0, 0, 0), anchor="mm")
    # Add color swatch gradient strip
    for x in range(400):
        t = x / 400
        r = int(rgb[0] * (0.5 + 0.5 * t))
        g = int(rgb[1] * (0.5 + 0.5 * t))
        b = int(rgb[2] * (0.5 + 0.5 * t))
        draw.line([(x, 0), (x, 245)], fill=(r, g, b))
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=90)
    return buf.getvalue()

def generate_shape_image(concept: Concept) -> bytes:
    img = Image.new("RGB", (400, 400), color=(245, 245, 245))
    draw = ImageDraw.Draw(img)
    cx, cy = 200, 200
    fill = (70, 130, 180)
    outline = (20, 60, 100)
    word = concept.word
    if word == "circle":
        draw.ellipse([cx-150, cy-150, cx+150, cy+150], fill=fill, outline=outline, width=4)
    elif word == "square":
        draw.rectangle([cx-130, cy-130, cx+130, cy+130], fill=fill, outline=outline, width=4)
    elif word == "triangle":
        draw.polygon([(cx, cy-150), (cx-140, cy+130), (cx+140, cy+130)],
                     fill=fill, outline=outline)
    elif word == "rectangle":
        draw.rectangle([cx-180, cy-100, cx+180, cy+100], fill=fill, outline=outline, width=4)
    elif word == "sphere":
        # Sphere illusion with shading
        draw.ellipse([cx-150, cy-150, cx+150, cy+150], fill=(100, 160, 220), outline=outline, width=3)
        draw.ellipse([cx-80, cy-90, cx+10, cy-20], fill=(200, 230, 255))
    # Label
    draw.text((200, 380), word.upper(), fill=(50, 50, 50), anchor="mm")
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=92)
    return buf.getvalue()

def generate_number_image(concept: Concept) -> bytes:
    num_map = {"zero": "0", "one": "1", "two": "2", "three": "3", "four": "4",
               "five": "5", "six": "6", "seven": "7", "eight": "8", "nine": "9",
               "ten": "10", "hundred": "100"}
    digit = num_map.get(concept.word, concept.word)
    img = Image.new("RGB", (400, 400), color=(250, 250, 248))
    draw = ImageDraw.Draw(img)
    # Draw digit large in center
    try:
        font = ImageFont.truetype("C:/Windows/Fonts/ariblk.ttf", 220)
    except Exception:
        font = ImageFont.load_default()
    draw.text((200, 200), digit, fill=(30, 30, 30), font=font, anchor="mm")
    draw.text((200, 375), f"  {concept.word.upper()}  ", fill=(100, 100, 100), anchor="mm")
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=92)
    return buf.getvalue()

def generate_text_card_image(concept: Concept) -> bytes:
    """
    Universal fallback: a clean text card with the word large, definition below,
    and a colored top/bottom stripe keyed to concept type.
    Used when no photo or domain-specific synthetic image is available.
    Semantically correct by construction -- the word and definition are written
    directly on the image.
    """
    TYPE_STRIPE = {
        "descriptor": (100, 149, 237),   # cornflower blue
        "abstract":   (147, 112, 219),   # medium purple
        "action":     ( 60, 179, 113),   # medium sea green
        "concrete":   (205, 133,  63),   # peru brown
    }
    stripe = TYPE_STRIPE.get(concept.type, (120, 120, 120))
    W, H = 480, 320
    img = Image.new("RGB", (W, H), color=(252, 251, 248))
    draw = ImageDraw.Draw(img)

    draw.rectangle([0, 0, W, 14], fill=stripe)
    draw.rectangle([0, H - 14, W, H], fill=stripe)

    try:
        font_word = ImageFont.truetype("C:/Windows/Fonts/arialbd.ttf", 72)
        font_def  = ImageFont.truetype("C:/Windows/Fonts/arial.ttf", 18)
    except Exception:
        font_word = ImageFont.load_default()
        font_def  = ImageFont.load_default()

    draw.text((W // 2, 80), concept.word.upper(),
              fill=(30, 30, 30), font=font_word, anchor="mm")

    # Word-wrap definition to ~50 chars per line
    words = concept.definition.split()
    lines: list[str] = []
    cur: list[str] = []
    for w in words:
        if len(" ".join(cur + [w])) > 52 and cur:
            lines.append(" ".join(cur))
            cur = [w]
        else:
            cur.append(w)
    if cur:
        lines.append(" ".join(cur))

    y = 160
    for line in lines[:4]:
        draw.text((W // 2, y), line, fill=(70, 70, 70), font=font_def, anchor="mm")
        y += 28

    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=90)
    return buf.getvalue()

def generate_synthetic(concept: Concept) -> Optional[bytes]:
    try:
        if concept.type == "color":
            return generate_color_image(concept)
        elif concept.type == "shape":
            return generate_shape_image(concept)
        elif concept.type == "number":
            return generate_number_image(concept)
    except Exception as e:
        print(f"  [WARN] synthetic generation failed for {concept.word}: {e}")
    return None

# ---------------------------------------------------------------------------
# Wikipedia image downloader
# ---------------------------------------------------------------------------

def download_wikipedia_image(wiki_title: str, client: httpx.Client) -> Optional[bytes]:
    """Fetch the main article thumbnail from Wikipedia REST API."""
    title = wiki_title.replace(" ", "_")
    try:
        r = client.get(
            f"https://en.wikipedia.org/api/rest_v1/page/summary/{title}",
            timeout=15, follow_redirects=True,
            headers={"User-Agent": "W1z4rDV1510n/1.0 (c4rr13rX@gmail.com; training pipeline)"},
        )
        if r.status_code != 200:
            return None
        data = r.json()
        thumb = data.get("thumbnail", {}).get("source")
        if not thumb:
            return None
        img_r = client.get(thumb, timeout=20, follow_redirects=True,
                           headers={"User-Agent": "W1z4rDV1510n/1.0 (c4rr13rX@gmail.com)"})
        if img_r.status_code == 200:
            return img_r.content
    except Exception:
        pass
    return None

def download_wikimedia_images(wiki_title: str, client: httpx.Client,
                               max_images: int = 3) -> list[bytes]:
    """Fetch up to max_images additional images from the Wikipedia media list."""
    title = wiki_title.replace(" ", "_")
    images: list[bytes] = []
    try:
        r = client.get(
            f"https://en.wikipedia.org/api/rest_v1/page/media-list/{title}",
            timeout=15, follow_redirects=True,
            headers={"User-Agent": "W1z4rDV1510n/1.0 (c4rr13rX@gmail.com)"},
        )
        if r.status_code != 200:
            return images
        items = r.json().get("items", [])
        for item in items:
            if len(images) >= max_images:
                break
            if item.get("type") != "image":
                continue
            srcset = item.get("srcset", [])
            url = None
            # Prefer the highest-res variant up to 640px wide
            for src in reversed(srcset):
                if int(src.get("width", 0)) <= 640:
                    url = src.get("src")
                    break
            if not url:
                continue
            if not url.startswith("http"):
                url = "https:" + url
            try:
                ir = client.get(url, timeout=20, follow_redirects=True,
                                headers={"User-Agent": "W1z4rDV1510n/1.0 (c4rr13rX@gmail.com)"})
                if ir.status_code == 200:
                    images.append(ir.content)
            except Exception:
                continue
    except Exception:
        pass
    return images

# ---------------------------------------------------------------------------
# Image quality validation -- STRICT gates
# ---------------------------------------------------------------------------

def validate_image(data: bytes, concept_word: str, generated: bool = False) -> tuple[bool, str]:
    """
    Return (ok, reason).  Every piece of image data must pass before training.
    Generated images skip the variance check (we control their content exactly).
    """
    # Generated images are correct by construction -- skip the byte-size gate
    # (a synthetic number on a plain background compresses to ~6 KB legitimately)
    if not generated and len(data) < MIN_FILE_BYTES:
        return False, f"too small ({len(data)} bytes < {MIN_FILE_BYTES})"
    try:
        img = Image.open(io.BytesIO(data)).convert("RGB")
    except Exception as e:
        return False, f"not decodable: {e}"
    w, h = img.size
    if w < MIN_IMAGE_W or h < MIN_IMAGE_H:
        return False, f"too small ({w}x{h})"
    if not generated:
        arr = np.array(img, dtype=np.float32)
        variance = float(np.var(arr))
        if variance < MIN_VARIANCE:
            return False, f"blank/solid (variance={variance:.1f})"
    return True, "ok"

# ---------------------------------------------------------------------------
# AWS Polly audio generation
# ---------------------------------------------------------------------------

def pcm_to_wav(pcm_bytes: bytes, sample_rate: int = 16000) -> bytes:
    data_size = len(pcm_bytes)
    header = struct.pack(
        "<4sI4s4sIHHIIHH4sI",
        b"RIFF", 36 + data_size, b"WAVE",
        b"fmt ", 16, 1, 1,       # PCM, mono
        sample_rate,
        sample_rate * 2,         # byte rate: sr * channels * bits/8
        2, 16,                   # block align, bits per sample
        b"data", data_size,
    )
    return header + pcm_bytes

def generate_audio(text: str, voice_id: str = "Matthew") -> Optional[bytes]:
    """Generate WAV audio via AWS Polly.  Returns None if unavailable."""
    if not _HAS_BOTO3:
        return None
    try:
        session = boto3.Session(profile_name=AWS_PROFILE, region_name=AWS_REGION)
        polly = session.client("polly")
        resp = polly.synthesize_speech(
            Text=text[:500],
            Engine="neural",
            VoiceId=voice_id,
            OutputFormat="pcm",
            SampleRate="16000",
        )
        pcm = resp["AudioStream"].read()
        return pcm_to_wav(pcm)
    except Exception as e:
        print(f"  [WARN] Polly failed for '{text[:30]}...': {e}")
        return None

# ---------------------------------------------------------------------------
# Keyboard typing helper
# ---------------------------------------------------------------------------

def keyboard_type(text: str, start_t: float = 0.0, delay: float = 0.11) -> list:
    """Simulate typing text character by character with realistic timing.
    Ends with a space so KeyboardBitsEncoder completes the word and emits
    the txt:word_* label that cross-activates with the image modality."""
    events = []
    t = start_t
    for ch in text:
        upper = ch.isupper()
        key = ch.lower()
        events.append({"key": key, "ctrl": False, "shift": upper, "alt": False, "t_secs": round(t, 3)})
        t += delay + (0.05 if ch == " " else 0.0)
    # Trailing space completes the last word
    if text and not text.endswith(" "):
        events.append({"key": " ", "ctrl": False, "shift": False, "alt": False, "t_secs": round(t, 3)})
    return events

# ---------------------------------------------------------------------------
# Scene compositor -- two concepts side by side with correct spatial labels
# ---------------------------------------------------------------------------

def compose_scene(img_left: bytes, img_right: bytes,
                  label_left: str, label_right: str) -> tuple[bytes, list]:
    """
    Place two concept images side by side on a white canvas.
    Returns (scene_jpeg_bytes, text_spans_positioned_at_object_centers).

    The spans have x_frac matching where the object ACTUALLY IS in the scene,
    so the txt:zone_* labels co-activate with the img:z*_* labels for that zone.
    """
    SZ = 280  # size for each object panel
    MARGIN = 20
    W = SZ * 2 + MARGIN * 3
    H = SZ + MARGIN * 2 + 40  # +40 for label row at bottom

    img_l = Image.open(io.BytesIO(img_left)).convert("RGB").resize((SZ, SZ))
    img_r = Image.open(io.BytesIO(img_right)).convert("RGB").resize((SZ, SZ))
    canvas = Image.new("RGB", (W, H), (255, 255, 255))
    canvas.paste(img_l, (MARGIN, MARGIN))
    canvas.paste(img_r, (SZ + MARGIN * 2, MARGIN))

    draw = ImageDraw.Draw(canvas)
    cx_l = (MARGIN + SZ // 2) / W
    cx_r = (SZ + MARGIN * 2 + SZ // 2) / W
    draw.text((int(cx_l * W), H - 20), label_left.upper(),  fill=(50, 50, 50), anchor="mm")
    draw.text((int(cx_r * W), H - 20), label_right.upper(), fill=(50, 50, 50), anchor="mm")

    buf = io.BytesIO()
    canvas.save(buf, format="JPEG", quality=88)

    spans = [
        {"text": label_left,  "role": "label", "bold": True, "italic": False,
         "size_ratio": 1.5, "indent": 0,
         "x_frac": round(cx_l, 3), "y_frac": 0.5,
         "seq_index": 0, "seq_total": 2},
        {"text": label_right, "role": "label", "bold": True, "italic": False,
         "size_ratio": 1.5, "indent": 0,
         "x_frac": round(cx_r, 3), "y_frac": 0.5,
         "seq_index": 1, "seq_total": 2},
    ]
    return buf.getvalue(), spans

# ---------------------------------------------------------------------------
# API helpers
# ---------------------------------------------------------------------------

def b64(data: bytes) -> str:
    return base64.b64encode(data).decode()

def api_train(client: httpx.Client, payload: dict, label: str = "") -> bool:
    try:
        r = client.post(f"{NODE_URL}/media/train", json=payload, timeout=30)
        if r.status_code == 200:
            return True
        print(f"  [ERR] train {label}: {r.status_code} {r.text[:80]}")
    except Exception as e:
        print(f"  [ERR] train {label}: {e}")
    return False

def api_train_sequence(client: httpx.Client, frames: list, tau: float = TEMP_TAU) -> bool:
    try:
        r = client.post(f"{NODE_URL}/media/train_sequence",
                        json={"frames": frames, "temporal_tau": tau}, timeout=60)
        return r.status_code == 200
    except Exception as e:
        print(f"  [ERR] train_sequence: {e}")
        return False

def api_ingest_qa(client: httpx.Client, candidates: list) -> int:
    try:
        r = client.post(f"{NODE_URL}/qa/ingest", json={"candidates": candidates}, timeout=15)
        if r.status_code == 200:
            return r.json().get("ingested", 0)
    except Exception:
        pass
    return 0

def api_record_episode(client: httpx.Client, context_labels: list[str],
                        predicted: str, actual: str, surprise: float = 0.0) -> bool:
    try:
        r = client.post(f"{NODE_URL}/neuro/record_episode", json={
            "context_labels": context_labels,
            "predicted": predicted,
            "actual": actual,
            "surprise": surprise,
        }, timeout=10)
        return r.status_code == 200
    except Exception:
        return False

def api_propagate(client: httpx.Client, seed_labels: list[str],
                   hops: int = 3, top_k: int = 10) -> list[dict]:
    try:
        r = client.post(f"{NODE_URL}/neuro/propagate", json={
            "seed_labels": seed_labels,
            "hops": hops,
            "min_strength": 0.005,
            "top_k": top_k,
        }, timeout=15)
        if r.status_code == 200:
            return r.json().get("activated", [])
    except Exception:
        pass
    return []

def api_qa_checkpoint(client: httpx.Client) -> bool:
    try:
        r = client.post(f"{NODE_URL}/qa/checkpoint", timeout=30)
        return r.status_code == 200
    except Exception:
        return False

# ---------------------------------------------------------------------------
# Per-concept training bundle
# ---------------------------------------------------------------------------

def train_concept(concept: Concept, images: list[bytes], audio: Optional[bytes],
                   client: httpx.Client, verbose: bool = False) -> dict:
    """
    Fire all modalities for one concept simultaneously, in the correct order:
      1. Anchor frame  -- image + label text + keyboard typing
      2. Definition    -- image + full definition + keyboard typing
      3. Audio frame   -- image + audio + text (if audio available)
      4. QA ingest     -- Hebbian Q->A pair with confidence 0.95
      5. Episode       -- record context->definition episode
    Returns stats dict.
    """
    word = concept.word
    defn = concept.definition
    stats = {"word": word, "frames": 0, "qa": 0, "audio": bool(audio)}

    if not images:
        print(f"  [SKIP] {word}: no valid images")
        return stats

    img0 = images[0]
    img1 = images[1] if len(images) > 1 else img0

    # -- 1. Anchor frame: image + bold label + keyboard typing ----------------
    spans_anchor = [{
        "text": word, "role": "label", "bold": True, "italic": False,
        "size_ratio": 2.0, "indent": 0,
        "x_frac": 0.5, "y_frac": 0.88,
        "seq_index": 0, "seq_total": 1,
    }]
    payload_anchor = {
        "modality": "page",
        "data_b64": b64(img0),
        "text": word,
        "spans": spans_anchor,
        "keys": keyboard_type(word),
        "lr_scale": LR_ANCHOR,
    }
    if api_train(client, payload_anchor, f"{word}:anchor"):
        stats["frames"] += 1

    # -- 2. Definition frame: different image + full definition + keyboard ----
    # Build structured text spans from definition sentences
    sentences = [s.strip() for s in defn.replace(".", ".|||").split("|||") if s.strip()]
    spans_def = []
    for i, sent in enumerate(sentences):
        spans_def.append({
            "text": sent, "role": "body", "bold": False, "italic": False,
            "size_ratio": 1.0, "indent": 0,
            "x_frac": 0.5, "y_frac": 0.2 + 0.15 * i,
            "seq_index": i, "seq_total": len(sentences),
        })
    # Add concept word as heading span
    spans_def.insert(0, {
        "text": word, "role": "heading", "bold": True, "italic": False,
        "size_ratio": 1.8, "indent": 0,
        "x_frac": 0.5, "y_frac": 0.05,
        "seq_index": 0, "seq_total": len(sentences) + 1,
    })

    payload_defn = {
        "modality": "page",
        "data_b64": b64(img1),
        "text": defn,
        "spans": spans_def,
        "keys": keyboard_type(defn[:80]),
        "lr_scale": LR_CONTEXT,
    }
    if api_train(client, payload_defn, f"{word}:defn"):
        stats["frames"] += 1

    # -- 3. Audio frame (if Polly generated it) --------------------------------
    if audio:
        payload_audio = {
            "modality": "full",
            "data_b64": b64(img0),
            "text": f"{word}. {concept.example}",
            "spans": spans_anchor,
            "lr_scale": LR_CONTEXT,
        }
        # Note: the audio modality endpoint expects audio data under a separate
        # field. We embed it as the data_b64 with modality="audio" in a separate call.
        payload_audio_only = {
            "modality": "audio",
            "data_b64": b64(audio),
            "text": word,
            "spans": spans_anchor,
            "lr_scale": LR_CONTEXT,
        }
        if api_train(client, payload_audio_only, f"{word}:audio"):
            stats["frames"] += 1

    # -- 4. Q&A ingest ---------------------------------------------------------
    qa_id = hashlib.sha256(f"streams|{word}|{defn}".encode()).hexdigest()[:16]
    ingested = api_ingest_qa(client, [{
        "qa_id": qa_id,
        "question": f"What is {word}?" if concept.type not in ("action", "descriptor") else f"What does {word} mean?",
        "answer": defn,
        "book_id": "concept_streams_v1",
        "page_index": 0,
        "confidence": 0.97,
        "evidence": defn,
        "review_status": "VERIFIED",
    }])
    stats["qa"] = ingested

    # -- 5. Episode recording (context label -> definition) --------------------
    api_record_episode(
        client,
        context_labels=[f"txt:word_{word}"],
        predicted=defn,
        actual=defn,
        surprise=0.0,
    )

    if verbose:
        print(f"  {word}: {stats['frames']} frames, qa={stats['qa']}, audio={stats['audio']}")
    return stats

# ---------------------------------------------------------------------------
# Temporal lifecycle trainer
# ---------------------------------------------------------------------------

def train_lifecycle_sequence(seq: list[str], client: httpx.Client,
                              all_images: dict[str, bytes]) -> bool:
    """Train a temporal concept chain as a train_sequence call.
    Frames are text-only if no image, image+text if available."""
    frames = []
    t = 0.0
    for word in seq:
        img = all_images.get(word)
        # No keyboard events here: lifecycle frames are conceptual-chain signals,
        # not typing simulations.  Keyboard events inflate the label count per frame
        # which makes the Hebbian bridge sets large and slows motif observation.
        frame = {
            "t_secs": round(t, 2),
            "modality": "page" if img else "text",
            "text": word,
            "spans": [{
                "text": word, "role": "label", "bold": True, "italic": False,
                "size_ratio": 1.5, "indent": 0,
                "x_frac": 0.5, "y_frac": 0.5,
                "seq_index": 0, "seq_total": 1,
            }],
            "lr_scale": LR_SEQ,
        }
        if img:
            frame["data_b64"] = b64(img)
        frames.append(frame)
        t += 2.0
    return api_train_sequence(client, frames, tau=TEMP_TAU)

# ---------------------------------------------------------------------------
# Scene composition trainer
# ---------------------------------------------------------------------------

def train_scene_pair(c_left: Concept, c_right: Concept,
                      img_left: bytes, img_right: bytes,
                      client: httpx.Client) -> bool:
    scene_bytes, spans = compose_scene(img_left, img_right, c_left.word, c_right.word)
    ok, reason = validate_image(scene_bytes, f"{c_left.word}+{c_right.word}", generated=True)
    if not ok:
        print(f"  [SKIP scene] {c_left.word}+{c_right.word}: {reason}")
        return False
    combined_text = f"{c_left.word} and {c_right.word}. {c_left.definition} {c_right.definition}"
    payload = {
        "modality": "page",
        "data_b64": b64(scene_bytes),
        "text": combined_text,
        "spans": spans,
        "keys": keyboard_type(f"{c_left.word} {c_right.word}"),
        "lr_scale": LR_SCENE,
    }
    return api_train(client, payload, f"scene:{c_left.word}+{c_right.word}")

# ---------------------------------------------------------------------------
# Meta-stream trainer
# ---------------------------------------------------------------------------

def train_meta_streams(client: httpx.Client) -> dict:
    counts = {}
    for domain, sequences in META_STREAMS.items():
        fired = 0
        for seq in sequences:
            frames = []
            t = 0.0
            for word in seq:
                # No keyboard events: meta-stream frames are domain-concept chains,
                # not typing simulations. Lean label sets keep bridge computation fast.
                frames.append({
                    "t_secs": round(t, 2),
                    "modality": "text",
                    "text": word,
                    "spans": [{
                        "text": word, "role": "body", "bold": False, "italic": False,
                        "size_ratio": 1.0, "indent": 0,
                        "x_frac": 0.5, "y_frac": 0.5,
                        "seq_index": 0, "seq_total": 1,
                    }],
                    "lr_scale": LR_SEQ,
                })
                t += 1.5
            if api_train_sequence(client, frames, tau=1.5):
                fired += 1
        counts[domain] = fired
        print(f"  {domain}: {fired}/{len(sequences)} sequences")
    return counts

# ---------------------------------------------------------------------------
# Cross-modal probe
# ---------------------------------------------------------------------------

def probe_cross_modal(concept: Concept, img_bytes: bytes, client: httpx.Client) -> dict:
    """
    Test whether image zone labels activate the correct text:word_ label,
    and whether the text:word_ label activates image zone labels.
    """
    word = concept.word
    results = {"word": word, "img_to_text": None, "text_to_img": None}

    # Extract image labels by encoding the image (request the node to encode it)
    # We probe by seeding with the word label and looking for image labels
    activated_from_text = api_propagate(client, [f"txt:word_{word}"], hops=3, top_k=15)
    img_labels = [a for a in activated_from_text if a["label"].startswith("img:")]
    txt_labels_from_text = [a for a in activated_from_text if "word_" in a["label"]]

    results["text_to_img"] = {
        "img_labels_activated": len(img_labels),
        "top_img": img_labels[:3],
        "related_words": [a["label"].replace("txt:word_", "") for a in txt_labels_from_text[:5]],
    }

    # Check if image-zone seeds activate the word (needs image encoded as labels)
    # Use hue labels from the concept's color if available
    if concept.color_rgb:
        # For color concepts: seed with the expected hue label
        import colorsys
        r, g, b = [x/255 for x in concept.color_rgb]
        h, s, v = colorsys.rgb_to_hsv(r, g, b)
        hue_bin = int(h * 16) % 16
        seeds = [f"img:h{hue_bin}"]
        activated_from_img = api_propagate(client, seeds, hops=3, top_k=15)
        word_labels = [a for a in activated_from_img if "word_" in a["label"]]
        results["img_to_text"] = {
            "seed": seeds,
            "word_labels_activated": len(word_labels),
            "top_words": [a["label"].replace("txt:word_", "") for a in word_labels[:5]],
        }
    return results

# ---------------------------------------------------------------------------
# Data preparation phase
# ---------------------------------------------------------------------------

def prep_concept_data(concepts: list[Concept], client: httpx.Client,
                      audio_enabled: bool = True, force: bool = False) -> dict[str, list[bytes]]:
    """
    Download / generate all images and audio for each concept.
    Validates strictly.  Saves to disk for reuse.
    Returns {concept_word: [validated_image_bytes, ...]}
    """
    all_images: dict[str, list[bytes]] = {}
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    for concept in concepts:
        word = concept.word
        concept_dir = DATA_DIR / word
        concept_dir.mkdir(exist_ok=True)
        manifest_path = concept_dir / "manifest.json"

        # Load cached manifest
        if manifest_path.exists() and not force:
            with open(manifest_path) as f:
                manifest = json.load(f)
            imgs = []
            for img_name in manifest.get("images", []):
                p = concept_dir / img_name
                if p.exists():
                    imgs.append(p.read_bytes())
            if imgs:
                all_images[word] = imgs
                print(f"  {word}: cached ({len(imgs)} images)")
                continue

        images_validated: list[bytes] = []
        image_names: list[str] = []

        # 1. Synthetic (abstract concepts) -- perfect quality guaranteed
        synthetic = generate_synthetic(concept)
        if synthetic:
            ok, reason = validate_image(synthetic, word, generated=True)
            if ok:
                fname = f"{word}_synth.jpg"
                (concept_dir / fname).write_bytes(synthetic)
                images_validated.append(synthetic)
                image_names.append(fname)

        # 2. Wikipedia main image (concrete/abstract concepts)
        if len(images_validated) < MAX_IMAGES_PER and concept.type not in ("number",):
            wiki_img = download_wikipedia_image(concept.wiki_title, client)
            if wiki_img:
                ok, reason = validate_image(wiki_img, word)
                if ok:
                    fname = f"{word}_wiki_0.jpg"
                    (concept_dir / fname).write_bytes(wiki_img)
                    images_validated.append(wiki_img)
                    image_names.append(fname)
                else:
                    print(f"  [REJECT] {word} wiki_main: {reason}")
            else:
                print(f"  [WARN] {word}: wiki thumbnail not available")

        # 3. Additional Wikimedia images
        if len(images_validated) < MAX_IMAGES_PER and concept.type in ("concrete", "action"):
            extras = download_wikimedia_images(concept.wiki_title, client,
                                               max_images=MAX_IMAGES_PER - len(images_validated))
            for i, extra in enumerate(extras):
                ok, reason = validate_image(extra, word)
                if ok:
                    fname = f"{word}_wiki_{i+1}.jpg"
                    (concept_dir / fname).write_bytes(extra)
                    images_validated.append(extra)
                    image_names.append(fname)
                else:
                    print(f"  [REJECT] {word} extra_{i}: {reason}")

        # 4. Text-card fallback -- guarantees every concept has at least one image
        if not images_validated:
            try:
                card = generate_text_card_image(concept)
                ok, reason = validate_image(card, word, generated=True)
                if ok:
                    fname = f"{word}_textcard.jpg"
                    (concept_dir / fname).write_bytes(card)
                    images_validated.append(card)
                    image_names.append(fname)
                    print(f"  [CARD] {word}: generated text-card fallback")
                else:
                    print(f"  [ERR] {word} text-card failed validation: {reason}")
            except Exception as e:
                print(f"  [ERR] {word} text-card generation: {e}")

        # 5. Audio (AWS Polly)
        if audio_enabled and _HAS_BOTO3:
            audio_path = concept_dir / f"{word}_matthew.wav"
            if not audio_path.exists() or force:
                audio = generate_audio(f"{word}. {concept.definition}", voice_id="Matthew")
                if audio:
                    audio_path.write_bytes(audio)
            audio_path2 = concept_dir / f"{word}_joanna.wav"
            if not audio_path2.exists() or force:
                audio2 = generate_audio(concept.example, voice_id="Joanna")
                if audio2:
                    audio_path2.write_bytes(audio2)

        # Save manifest
        with open(manifest_path, "w") as f:
            json.dump({"word": word, "type": concept.type,
                        "images": image_names, "validated": len(images_validated)}, f)

        all_images[word] = images_validated
        icon = "[OK]" if images_validated else "[XX]"
        print(f"  {icon} {word}: {len(images_validated)} images")
        time.sleep(0.15)  # polite rate limit for Wikipedia

    return all_images

# ---------------------------------------------------------------------------
# Archive.org video pipeline
# ---------------------------------------------------------------------------

def fetch_archive_videos(query: str = "prelinger",
                          collection: str = "prelinger",
                          max_items: int = 5,
                          client: Optional[httpx.Client] = None) -> list[dict]:
    """
    Search Archive.org for relevant educational/ephemeral films.
    Returns list of {identifier, title, description, download_url}.
    """
    if client is None:
        client = httpx.Client()
    try:
        r = client.get(
            "https://archive.org/advancedsearch.php",
            params={
                "q": f"collection:{collection} AND {query}",
                "fl[]": ["identifier", "title", "description"],
                "mediatype": "movies",
                "output": "json",
                "rows": max_items,
                "page": 1,
            },
            timeout=20,
        )
        docs = r.json().get("response", {}).get("docs", [])
        results = []
        for doc in docs:
            iid = doc.get("identifier", "")
            # Get download info
            meta_r = client.get(f"https://archive.org/metadata/{iid}", timeout=15)
            files = meta_r.json().get("files", [])
            video_url = None
            for f in files:
                name = f.get("name", "")
                if name.endswith(".mp4") or name.endswith(".mpeg"):
                    video_url = f"https://archive.org/download/{iid}/{name}"
                    break
            if video_url:
                results.append({
                    "identifier": iid,
                    "title": doc.get("title", iid),
                    "description": str(doc.get("description", ""))[:200],
                    "download_url": video_url,
                })
        return results
    except Exception as e:
        print(f"  [ERR] archive search: {e}")
        return []

def extract_video_frames(video_path: Path, fps: float = 1.0,
                          audio_sr: int = 16000) -> tuple[list[bytes], Optional[bytes]]:
    """
    Extract frames at fps and audio from a video using ffmpeg.
    Returns (frame_jpeg_list, audio_wav_bytes).
    """
    import subprocess, tempfile, glob
    frames_dir = video_path.parent / f"{video_path.stem}_frames"
    frames_dir.mkdir(exist_ok=True)
    # Extract frames
    cmd_frames = [
        "ffmpeg", "-i", str(video_path), "-vf", f"fps={fps}",
        "-q:v", "5", str(frames_dir / "%06d.jpg"), "-y", "-loglevel", "error"
    ]
    subprocess.run(cmd_frames, check=False)
    frame_files = sorted(glob.glob(str(frames_dir / "*.jpg")))
    frames = []
    for p in frame_files[:120]:  # cap at 2 minutes at 1fps
        data = Path(p).read_bytes()
        ok, _ = validate_image(data, "video_frame")
        if ok:
            frames.append(data)

    # Extract audio as 16kHz mono WAV
    audio_path = video_path.parent / f"{video_path.stem}_audio.wav"
    cmd_audio = [
        "ffmpeg", "-i", str(video_path),
        "-ar", str(audio_sr), "-ac", "1", "-f", "wav",
        str(audio_path), "-y", "-loglevel", "error"
    ]
    subprocess.run(cmd_audio, check=False)
    audio_wav = audio_path.read_bytes() if audio_path.exists() else None

    return frames, audio_wav

def train_video_stream(title: str, frames: list[bytes], audio_wav: Optional[bytes],
                        client: httpx.Client, chunk_size: int = 8) -> int:
    """
    Train a video as overlapping temporal sequences of frames.
    Each chunk of chunk_size frames = one train_sequence call.
    Audio chunks are paired with frame chunks if available.
    Returns number of sequences trained.
    """
    trained = 0
    step = max(1, chunk_size // 2)  # 50% overlap for temporal coherence
    for start in range(0, len(frames) - 1, step):
        chunk = frames[start:start + chunk_size]
        if len(chunk) < 2:
            break
        frame_payloads = []
        for i, img in enumerate(chunk):
            t = float(i) / 1.0  # 1fps -> 1s per frame
            frame_payloads.append({
                "t_secs": round(t, 2),
                "modality": "image",
                "data_b64": b64(img),
                "lr_scale": LR_SEQ,
            })
        if api_train_sequence(client, frame_payloads, tau=3.0):
            trained += 1
    return trained

# ---------------------------------------------------------------------------
# Main orchestration
# ---------------------------------------------------------------------------

def run(args):
    node_ok = False
    try:
        r = httpx.get(f"{NODE_URL}/health", timeout=5)
        if r.json().get("status") == "OK":
            node_ok = True
            print(f"Node: {r.json().get('node_id')}  uptime={r.json().get('uptime_secs')}s")
    except Exception:
        pass

    if not node_ok and not args.prep_only:
        sys.exit(f"Node not reachable at {NODE_URL}. Start it first.")

    # Select concepts
    if args.concepts == "all":
        selected = CONCEPTS
    else:
        try:
            n = int(args.concepts)
            selected = CONCEPTS[:n]
        except ValueError:
            words = [w.strip() for w in args.concepts.split(",")]
            selected = [c for c in CONCEPTS if c.word in words]

    print(f"\n{'='*60}")
    print(f"Concepts selected: {len(selected)}")
    print(f"Audio (Polly):     {'enabled' if _HAS_BOTO3 else 'disabled (no boto3)'}")
    print(f"Scene pairs:       {sum(1 for a,b in SCENE_PAIRS if any(c.word==a for c in selected) and any(c.word==b for c in selected))}")
    print(f"Meta-streams:      {len(META_STREAMS)} domains, {sum(len(v) for v in META_STREAMS.values())} sequences")
    print(f"{'='*60}\n")

    with httpx.Client() as client:
        # -- PREP ------------------------------------------------------------
        print("PHASE 1: DATA PREPARATION (strict validation)")
        print("-" * 42)
        all_images = prep_concept_data(
            selected, client,
            audio_enabled=(not args.no_audio),
            force=args.force_prep,
        )

        total_imgs = sum(len(v) for v in all_images.values())
        valid_concepts = [c for c in selected if all_images.get(c.word)]
        print(f"\nPREP complete: {total_imgs} validated images across {len(valid_concepts)} concepts\n")

        if args.prep_only:
            return

        # -- TRAIN CONCEPTS --------------------------------------------------
        print("PHASE 2: CONCEPT STREAM TRAINING (all modalities)")
        print("-" * 50)
        qa_batch = []
        for concept in valid_concepts:
            imgs = all_images[concept.word]
            audio = None
            audio_path = DATA_DIR / concept.word / f"{concept.word}_matthew.wav"
            if audio_path.exists():
                audio = audio_path.read_bytes()
            stats = train_concept(concept, imgs, audio, client, verbose=args.verbose)
            print(f"  [OK] {concept.word:<16} {stats['frames']} frames  audio={'y' if stats['audio'] else 'n'}")
            time.sleep(0.05)

        # -- LIFECYCLE SEQUENCES ---------------------------------------------
        print("\nPHASE 3: TEMPORAL LIFECYCLE SEQUENCES")
        print("-" * 40)
        # Build a flat map of best image per concept word
        best_img: dict[str, bytes] = {}
        for c in valid_concepts:
            imgs = all_images.get(c.word, [])
            if imgs:
                best_img[c.word] = imgs[0]

        for seq in LIFECYCLE_SEQUENCES:
            result = train_lifecycle_sequence(seq, client, best_img)
            icon = "[OK]" if result else "[XX]"
            print(f"  {icon} {' -> '.join(seq[:4])}{'-> ...' if len(seq)>4 else ''}")

        # -- SCENE COMPOSITIONS ----------------------------------------------
        print("\nPHASE 4: SCENE COMPOSITION (spatial decomposition)")
        print("-" * 50)
        for word_l, word_r in SCENE_PAIRS:
            c_l = next((c for c in selected if c.word == word_l), None)
            c_r = next((c for c in selected if c.word == word_r), None)
            if not c_l or not c_r:
                continue
            imgs_l = all_images.get(word_l, [])
            imgs_r = all_images.get(word_r, [])
            if not imgs_l or not imgs_r:
                continue
            result = train_scene_pair(c_l, c_r, imgs_l[0], imgs_r[0], client)
            icon = "[OK]" if result else "[XX]"
            print(f"  {icon} {word_l} <-> {word_r}")

        # -- META-STREAMS ----------------------------------------------------
        print("\nPHASE 5: DOMAIN META-STREAMS")
        print("-" * 30)
        train_meta_streams(client)

        # -- QA CHECKPOINT ---------------------------------------------------
        print("\nSaving QA store...")
        if api_qa_checkpoint(client):
            print("  QA store saved.")

        # -- PROBE -----------------------------------------------------------
        if not args.skip_probe:
            print("\nPHASE 6: CROSS-MODAL PROBE")
            print("-" * 30)
            probe_words = ["apple", "red", "circle", "dog", "water", "gravity", "learn"]
            for word in probe_words:
                c = next((x for x in selected if x.word == word), None)
                if not c:
                    continue
                imgs = all_images.get(word, [])
                img = imgs[0] if imgs else None
                result = probe_cross_modal(c, img, client)
                text_to_img = result.get("text_to_img", {})
                n_img = text_to_img.get("img_labels_activated", 0)
                related = text_to_img.get("related_words", [])
                print(f"  '{word}' -> {n_img} img labels fire | related: {related[:4]}")

    # -- VIDEO PIPELINE (optional) --------------------------------------------
    if args.video_prep or args.video_train:
        print("\nPHASE 7: ARCHIVE.ORG VIDEO PIPELINE")
        print("-" * 40)
        VIDEO_DIR.mkdir(parents=True, exist_ok=True)
        with httpx.Client() as vc:
            items = fetch_archive_videos(
                query=args.video_query,
                collection="prelinger",
                max_items=args.video_max,
                client=vc,
            )
            print(f"  Found {len(items)} videos")
            for item in items:
                print(f"  -> {item['title']}")
                video_file = VIDEO_DIR / f"{item['identifier']}.mp4"
                if args.video_train and not video_file.exists():
                    print(f"    Downloading...")
                    try:
                        with vc.stream("GET", item["download_url"], timeout=300) as r:
                            with open(video_file, "wb") as f:
                                for chunk in r.iter_bytes(chunk_size=1024*64):
                                    f.write(chunk)
                    except Exception as e:
                        print(f"    [ERR] {e}")
                        continue
                if args.video_train and video_file.exists():
                    frames, audio = extract_video_frames(video_file, fps=args.video_fps)
                    print(f"    {len(frames)} frames extracted")
                    if frames:
                        with httpx.Client() as tc:
                            n = train_video_stream(item["title"], frames, audio, tc)
                            print(f"    {n} sequences trained")

    print("\nDONE.")

# ---------------------------------------------------------------------------

if __name__ == "__main__":
    p = argparse.ArgumentParser(description="Rich multi-modal concept stream trainer")
    p.add_argument("--node",         default=NODE_URL)
    p.add_argument("--concepts",     default="10",
                   help="Number, 'all', or comma-separated words")
    p.add_argument("--prep-only",    action="store_true")
    p.add_argument("--probe-only",   action="store_true")
    p.add_argument("--skip-probe",   action="store_true")
    p.add_argument("--no-audio",     action="store_true")
    p.add_argument("--force-prep",   action="store_true", help="Re-download even if cached")
    p.add_argument("--verbose",      action="store_true")
    p.add_argument("--video-prep",   action="store_true", help="Search Archive.org for videos")
    p.add_argument("--video-train",  action="store_true", help="Download and train videos")
    p.add_argument("--video-query",  default="nature animals everyday life education")
    p.add_argument("--video-max",    type=int, default=3)
    p.add_argument("--video-fps",    type=float, default=1.0)
    args = p.parse_args()

    if args.node != NODE_URL:
        NODE_URL = args.node

    run(args)
