/// Threat overlay — unified output combining all threat sub-systems.
///
/// The overlay is the single API-facing output type.  It merges:
///
///   ThreatField       — spatial heat map of the scene
///   ConsensusSnapshot — multi-entity wave-function state
///   IntentSignals     — per-entity intent distribution + predicted impacts
///   SubUltradianState — arousal band readings per entity
///   EntityHealthState — current 6D health + color per entity
///   HealthPredictions — forward-projected health deltas if threat materialises
///
/// The overlay is produced once per sensor frame by `ThreatOverlayEngine` and
/// serialised as JSON for the HTTP `/threat/overlay` endpoint.

use crate::schema::Timestamp;
use crate::threat::{
    consensus::ConsensusSnapshot,
    field::ThreatField,
    health::EntityHealthState,
    intent::IntentSignal,
    subradian::SubUltradianState,
};
use serde::{Deserialize, Serialize};

// ─── Health prediction ────────────────────────────────────────────────────────

/// A forward-projected health impact on a specific entity + dimension.
///
/// Generated by mapping `PredictedHealthImpact` values from intent signals
/// through the propagation graph to estimate downstream consequences.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthPrediction {
    /// The entity that would be affected.
    pub entity_id: String,
    /// Human-readable scope label (e.g. "organism", "torso").
    pub scope_label: String,
    /// Which dimension is impacted (0=SI, 1=EF, 2=RC, 3=FO, 4=AR, 5=TC).
    pub dimension_index: usize,
    /// Expected delta [−1, 0] — always negative (predictions are harm-only).
    pub delta: f32,
    /// How confident we are in this prediction [0, 1].
    pub confidence: f32,
    /// Seconds until impact is estimated to materialise.
    pub time_horizon_secs: f32,
    /// The intent class that drives this prediction.
    pub driver_intent: String,
}

// ─── Entity summary ───────────────────────────────────────────────────────────

/// Per-entity summary within the overlay — rolls up all sub-system readings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntityOverlaySummary {
    pub entity_id: String,
    /// Current health state (per-scope vectors + organism color).
    pub health: EntityHealthState,
    /// Current intent reading.
    pub intent: Option<IntentSignal>,
    /// Sub-ultradian arousal state.
    pub arousal: Option<SubUltradianState>,
    /// Threat score derived from intent + arousal (composite [0,1]).
    pub composite_threat: f32,
    /// Hex color representing composite threat (red spectrum).
    pub threat_color: String,
    /// Predicted health impacts if dominant intent materialises.
    pub predictions: Vec<HealthPrediction>,
}

impl EntityOverlaySummary {
    fn composite_threat(intent: Option<&IntentSignal>, arousal: Option<&SubUltradianState>) -> f32 {
        let intent_score = intent.map(|i| i.threat_score).unwrap_or(0.0);
        let arousal_score = arousal.map(|a| a.combined_arousal).unwrap_or(0.0);
        // Intent is the primary signal; arousal amplifies it slightly.
        (intent_score * 0.75 + arousal_score * 0.25).clamp(0.0, 1.0)
    }

    /// Build a summary from individual sub-system outputs.
    pub fn build(
        entity_id: String,
        health: EntityHealthState,
        intent: Option<IntentSignal>,
        arousal: Option<SubUltradianState>,
    ) -> Self {
        let composite_threat = Self::composite_threat(intent.as_ref(), arousal.as_ref());
        let threat_color = threat_color_hex(composite_threat);

        // Map PredictedHealthImpact → HealthPrediction.
        let predictions: Vec<HealthPrediction> = intent.as_ref()
            .map(|sig| {
                sig.predicted_impacts.iter().map(|imp| HealthPrediction {
                    entity_id: imp.entity_id.clone(),
                    scope_label: "organism".to_string(),
                    dimension_index: imp.dimension_index,
                    delta: imp.delta,
                    confidence: imp.confidence,
                    time_horizon_secs: imp.time_horizon_secs,
                    driver_intent: sig.dominant_intent.label().to_string(),
                }).collect()
            })
            .unwrap_or_default();

        Self { entity_id, health, intent, arousal, composite_threat, threat_color, predictions }
    }
}

// ─── Full overlay ─────────────────────────────────────────────────────────────

/// The complete threat overlay for one sensor frame.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThreatOverlay {
    pub timestamp: Timestamp,
    /// Spatial threat heat map over the scene.
    pub field: ThreatField,
    /// Multi-entity wave-function / consensus state.
    pub consensus: ConsensusSnapshot,
    /// Per-entity rolled-up summaries.
    pub entities: Vec<EntityOverlaySummary>,
    /// Overall scene alarm level: "none", "low", "medium", "high", "critical".
    pub scene_alarm: String,
    /// Scene-level hex color encoding the current threat state.
    pub scene_color: String,
    /// Number of entities in elevated threat state.
    pub threat_entity_count: usize,
}

impl ThreatOverlay {
    /// Build the overlay from all sub-system outputs.
    pub fn build(
        timestamp: Timestamp,
        field: ThreatField,
        consensus: ConsensusSnapshot,
        entities: Vec<EntityOverlaySummary>,
    ) -> Self {
        let threat_entity_count = entities.iter().filter(|e| e.composite_threat > 0.15).count();

        // Scene alarm is driven by consensus.
        let scene_alarm = consensus.alarm_level.clone();
        let scene_color = alarm_color_hex(&scene_alarm, consensus.consensus_confidence);

        Self { timestamp, field, consensus, entities, scene_alarm, scene_color, threat_entity_count }
    }

    /// Convenience: are any entities at critical threat?
    pub fn has_critical(&self) -> bool {
        self.scene_alarm == "critical"
            || self.entities.iter().any(|e| e.composite_threat >= 0.80)
    }

    /// Return all health predictions sorted by |delta| descending.
    pub fn all_predictions_ranked(&self) -> Vec<&HealthPrediction> {
        let mut preds: Vec<&HealthPrediction> = self.entities.iter()
            .flat_map(|e| e.predictions.iter())
            .collect();
        preds.sort_by(|a, b| b.delta.abs().partial_cmp(&a.delta.abs()).unwrap());
        preds
    }
}

// ─── Color helpers ────────────────────────────────────────────────────────────

/// Map composite threat [0,1] → red-spectrum hex color.
/// 0.0 = green (#00cc44), 0.5 = orange (#ff8800), 1.0 = red (#ff1100).
fn threat_color_hex(t: f32) -> String {
    let t = t.clamp(0.0, 1.0);
    // Hue: 120° (green) → 0° (red) as threat rises.
    let hue = 120.0 * (1.0 - t);
    let (r, g, b) = crate::threat::health::hsv_to_rgb(hue, 0.85, 0.9);
    format!("#{:02x}{:02x}{:02x}", r, g, b)
}

/// Map alarm level → representative color.
fn alarm_color_hex(level: &str, confidence: f32) -> String {
    match level {
        "critical" => "#ff1100".to_string(),
        "high"     => "#ff6600".to_string(),
        "medium"   => "#ffaa00".to_string(),
        "low"      => "#ccee00".to_string(),
        _          => {
            // "none" — shade of green reflecting how un-threatening the scene is.
            let brightness = (0.4 + 0.6 * (1.0 - confidence)).clamp(0.0, 1.0);
            let v = (brightness * 255.0) as u8;
            format!("#00{:02x}00", v)
        }
    }
}

// ─── Overlay engine ───────────────────────────────────────────────────────────

/// Assembles a `ThreatOverlay` from live sub-system references.
///
/// The engine itself is stateless — it simply combines whatever outputs the
/// sub-systems provide.  State lives inside each sub-system engine.
#[derive(Debug, Default)]
pub struct ThreatOverlayEngine;

impl ThreatOverlayEngine {
    pub fn new() -> Self { Self }

    /// Assemble a full overlay from the provided sub-system outputs.
    ///
    /// Arguments:
    ///   `timestamp`   — current frame time
    ///   `field`       — spatial threat field snapshot
    ///   `consensus`   — consensus engine output
    ///   `intents`     — intent signal per entity (may be empty)
    ///   `arousals`    — sub-ultradian state per entity (may be empty)
    ///   `healths`     — entity health state per entity (may be empty)
    pub fn assemble(
        &self,
        timestamp: Timestamp,
        field: ThreatField,
        consensus: ConsensusSnapshot,
        intents: Vec<IntentSignal>,
        arousals: Vec<SubUltradianState>,
        healths: Vec<EntityHealthState>,
    ) -> ThreatOverlay {
        // Index by entity_id for O(1) lookup.
        let intent_map: std::collections::HashMap<String, IntentSignal> = intents
            .into_iter().map(|s| (s.entity_id.clone(), s)).collect();
        let arousal_map: std::collections::HashMap<String, SubUltradianState> = arousals
            .into_iter().map(|s| (s.entity_id.clone(), s)).collect();

        // Collect all entity IDs from all sources.
        let mut entity_ids: std::collections::HashSet<String> = std::collections::HashSet::new();
        for h in &healths          { entity_ids.insert(h.entity_id.clone()); }
        for k in intent_map.keys() { entity_ids.insert(k.clone()); }
        for k in arousal_map.keys(){ entity_ids.insert(k.clone()); }

        // Build per-entity summaries.
        // Where no health state exists, emit a placeholder.
        let health_map: std::collections::HashMap<String, EntityHealthState> = healths
            .into_iter().map(|h| (h.entity_id.clone(), h)).collect();

        let entities: Vec<EntityOverlaySummary> = entity_ids.into_iter().map(|eid| {
            let health = health_map.get(&eid).cloned()
                .unwrap_or_else(|| EntityHealthState::new(eid.clone(), "unknown"));
            let intent  = intent_map.get(&eid).cloned();
            let arousal = arousal_map.get(&eid).cloned();
            EntityOverlaySummary::build(eid, health, intent, arousal)
        }).collect();

        ThreatOverlay::build(timestamp, field, consensus, entities)
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::Timestamp;
    use crate::threat::{
        consensus::ConsensusSnapshot,
        field::ThreatField,
        health::EntityHealthState,
    };

    fn ts() -> Timestamp { Timestamp { unix: 0 } }

    fn empty_field() -> ThreatField {
        ThreatField::empty(ts())
    }

    #[test]
    fn empty_overlay_builds_without_panic() {
        let engine = ThreatOverlayEngine::new();
        let overlay = engine.assemble(
            ts(),
            empty_field(),
            ConsensusSnapshot::empty(ts()),
            vec![], vec![], vec![],
        );
        assert_eq!(overlay.scene_alarm, "none");
        assert_eq!(overlay.entities.len(), 0);
        assert!(!overlay.has_critical());
    }

    #[test]
    fn entity_with_health_appears_in_overlay() {
        let engine = ThreatOverlayEngine::new();
        let mut h = EntityHealthState::new("person_1".to_string(), "human");
        h.organism_score = 0.8;
        h.organism_color = "#ccffcc".to_string();
        let overlay = engine.assemble(
            ts(),
            empty_field(),
            ConsensusSnapshot::empty(ts()),
            vec![], vec![], vec![h],
        );
        assert_eq!(overlay.entities.len(), 1);
        assert_eq!(overlay.entities[0].entity_id, "person_1");
    }

    #[test]
    fn threat_color_extreme_values() {
        // No threat → greenish.
        let green = threat_color_hex(0.0);
        assert!(green.starts_with('#'));
        // Full threat → reddish.
        let red = threat_color_hex(1.0);
        assert!(red.starts_with('#'));
        // They must differ.
        assert_ne!(green, red);
    }

    #[test]
    fn predictions_ranked_by_delta() {
        let engine = ThreatOverlayEngine::new();
        // Build an intent signal with predictions.
        use crate::threat::intent::{IntentClass, IntentSignal, PredictedHealthImpact};
        use std::collections::HashMap;
        let sig = IntentSignal {
            entity_id: "attacker".to_string(),
            distribution: HashMap::new(),
            dominant_intent: IntentClass::DirectThreat,
            dominant_confidence: 0.9,
            threat_score: 0.9,
            target_entities: vec!["victim".to_string()],
            predicted_impacts: vec![
                PredictedHealthImpact { entity_id: "victim".to_string(), dimension_index: 0, delta: -0.3, time_horizon_secs: 2.0, confidence: 0.9 },
                PredictedHealthImpact { entity_id: "victim".to_string(), dimension_index: 4, delta: -0.8, time_horizon_secs: 5.0, confidence: 0.7 },
            ],
            timestamp: ts(),
        };
        let overlay = engine.assemble(
            ts(),
            empty_field(),
            ConsensusSnapshot::empty(ts()),
            vec![sig], vec![], vec![],
        );
        let ranked = overlay.all_predictions_ranked();
        // -0.8 should come first.
        assert!(!ranked.is_empty());
        assert!((ranked[0].delta + 0.8).abs() < 1e-4, "got {}", ranked[0].delta);
    }
}
